version: '3'
services:
  front:
    build:
      args:
        APP_ENV: "$ENV"
      context: .
      dockerfile: front/Dockerfile
    links:
      - api
    ports:
      - "$FRONT_PORT:3000"
    restart: always

  api:
    build:
      args:
        APP_ENV: "$ENV"
      context: .
      dockerfile: api/Dockerfile
    links:
      - mysql
    ports:
      - "$API_PORT:3000"
    restart: always

  mysql:
    build:
      context: .
      dockerfile: mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASS
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASS
      MYSQL_DATABASE: $MYSQL_DB
      TZ: "Asia/Tokyo"
    ports:
      - "$MYSQL_PORT:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
