version: 2
jobs:
  generate_cache:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: docker-{{ checksum ".circleci/config.yml" }}-{{ checksum "docker-compose.yml" }}-{{ checksum "api/Dockerfile" }}-{{ checksum "front/Dockerfile" }}-{{ checksum "mysql/Dockerfile" }} 
          paths: ~/caches/images.tar
      - run:
          name: Check cache file, if not exists then pull images and generate cache.
          command: |
            if [ ! -f ~/caches/images.tar ]; then
              docker-compose -f docker-compose.yml pull
              docker-compose -f docker-compose.yml build
              mkdir -p ~/caches
              docker save $(docker images | awk 'NR>=2 && ! /^<none>/{print $1}') -o ~/caches/images.tar
            fi
      - save_cache:
          key: docker-{{ checksum ".circleci/config.yml" }}-{{ checksum "docker-compose.yml" }}-{{ checksum "api/Dockerfile" }}-{{ checksum "front/Dockerfile" }}-{{ checksum "mysql/Dockerfile" }} 
          paths: ~/caches/images.tar
      - run:
          name: finish cacheing
          command: echo "finish cache"

  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker-compose -f docker-compose.test.yml build
      - run:
            name: docker-compose up
            command: |
                 docker-compose -f docker-compose.test.yml up -d
      - run:
            name: finish build
            command: echo "finish build"

  push-image:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: docker-{{ checksum ".circleci/config.yml" }}-{{ checksum "docker-compose.yml" }}-{{ checksum "api/Dockerfile" }}-{{ checksum "front/Dockerfile" }}-{{ checksum "mysql/Dockerfile" }} 
          paths: ~/caches/images.tar
      - run: 
          name: docker load
          command: if test -d ~/caches; then docker load -i ~/caches/images.tar; fi
      - run: 
          name: build api image 
          command: |
            docker build -f api/Dockerfile --rm=false -t hoge/hoge:latest .
      - run: 
          name: push api image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push hoge/hoge:latest
      - run: 
          name: build front image 
          command: |
            docker build -f front/Dockerfile --rm=false -t huga/huga:latest .
      - run: 
          name: push front image
          command: |
            docker push huga/huga:latest


  deploy:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "fingerprints"
      - run:
          name: Start ssh-keyscan
          command: |
            ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "docker pull hoge/hoge:latest && docker stop hoge && docker rm hoge && docker run -e APP_ENV=prod --name hoge -itd -p 3000:3000 hoge/hoge:latest && docker pull huga/huga:latest && docker stop huga && docker rm huga && docker run -e APP_ENV=prod --name huga -itd -p 3001:3000 huga/huga:latest"
      - run:
          name: Exit from SSH
          command: exit
      - run:
          name: finish deploy
          command: echo "finish deploy"


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - generate_cache
      - build:
          requires:
            - generate_cache
      - push-image:
          filters:
            branches:
              only: master
          requires:
            - build
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - push-image
