name: build-and-deploy-prod

on:
  push:
    branches:
      - master

jobs:

  build:
    name: test build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - run: cp .env.example .env
      - name: build
        run: docker-compose build --no-cache && docker-compose up -d 

  deploy:
    name: deploy to prod
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: ssh and deploy
        uses: im-neko/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_KEY }}
          port: ${{ secrets.PROD_PORT }}
          script: |
            cd /var/webapp-template &&
            sudo git pull origin master &&
            docker-compose build --no-cache &&
            docker-compose up -d 
